CREATE TABLE RECIPES (
  ID               INTEGER PRIMARY KEY AUTOINCREMENT,
  TITLE            TEXT NOT NULL,
  IMAGE            TEXT NOT NULL,
  SOURCE           TEXT NOT NULL,
  STEPS            TEXT,
  SERVINGS         INT,
  CALS_PER_SERVING INT
);

CREATE TABLE INGREDIENTS (
  ID   INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL
);

CREATE TABLE RECIPE_TO_INGREDIENT (
  ID            INTEGER PRIMARY KEY AUTOINCREMENT,
  RECIPE_ID     INT REFERENCES RECIPES (ID),
  INGREDIENT_ID INT REFERENCES INGREDIENTS (ID),
  QUANTITY      TEXT NOT NULL
);

CREATE TABLE TAGS (
  ID   INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL
);

CREATE TABLE RECIPE_TO_TAG (
  ID        INTEGER PRIMARY KEY AUTOINCREMENT,
  RECIPE_ID INT REFERENCES RECIPES (ID),
  TAG_ID    INT REFERENCES TAGS (ID)
);

CREATE TABLE USER (
  ID       INTEGER PRIMARY KEY AUTOINCREMENT,
  USERNAME TEXT NOT NULL,
  PASSWORD TEXT NOT NULL
);

CREATE TABLE USER_TO_RECIPE (
  ID        INTEGER PRIMARY KEY AUTOINCREMENT,
  USER_ID   INT REFERENCES USER (ID),
  RECIPE_ID INT REFERENCES RECIPES (ID),
  DID_RATE INT,
  RATING INT,
  DID_SAVE INT
);

